// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCVX3GH7uqmh71QbR51c73kHpLn1CSgY',
    appId: '1:980974360453:web:5307e2e01da6c4817dd6ec',
    messagingSenderId: '980974360453',
    projectId: 'bhaamma-foods-rider',
    authDomain: 'bhaamma-foods-rider.firebaseapp.com',
    storageBucket: 'bhaamma-foods-rider.firebasestorage.app',
    measurementId: 'G-216PSEDJD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGGKIFlgXagXQ30tDST3SkBp2QgREKGM',
    appId: '1:980974360453:android:be3a4a63ef8e683e7dd6ec',
    messagingSenderId: '980974360453',
    projectId: 'bhaamma-foods-rider',
    storageBucket: 'bhaamma-foods-rider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57CVMQxgXiWog_rNgtvLfudpsB7_SSt4',
    appId: '1:980974360453:ios:8fedef71733ccc817dd6ec',
    messagingSenderId: '980974360453',
    projectId: 'bhaamma-foods-rider',
    storageBucket: 'bhaamma-foods-rider.firebasestorage.app',
    iosBundleId: 'com.example.bhammaDeliveryBoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57CVMQxgXiWog_rNgtvLfudpsB7_SSt4',
    appId: '1:980974360453:ios:8fedef71733ccc817dd6ec',
    messagingSenderId: '980974360453',
    projectId: 'bhaamma-foods-rider',
    storageBucket: 'bhaamma-foods-rider.firebasestorage.app',
    iosBundleId: 'com.example.bhammaDeliveryBoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMCVX3GH7uqmh71QbR51c73kHpLn1CSgY',
    appId: '1:980974360453:web:3c232d61343e68487dd6ec',
    messagingSenderId: '980974360453',
    projectId: 'bhaamma-foods-rider',
    authDomain: 'bhaamma-foods-rider.firebaseapp.com',
    storageBucket: 'bhaamma-foods-rider.firebasestorage.app',
    measurementId: 'G-B7MT71V5WL',
  );

}