const String AppsLogo ="assets/images/bhamma.jpg";
//const String baseUrl = "https://foodport.equi.website/api/";
const String baseUrl = "https://admin.bhaammafoods.in/api/";
const String imageUrl = "https://admin.bhaammafoods.in/";
const String imageUrlstorage = "https://admin.bhaammafoods.in/storage/";

const String login = "login"; //
const String registration = "delivery-man/deliveryreg";//
const String getDeliveryBoyDetails = "delivery-man/getdeliveryboy";
const String updateDeliveryBoyDetails = "delivery-man/delivupdate";
const String getVehicleList = "delivery-man/vehicle-type"; //
const String getZoneList = "zone"; //
const String getBankList = "banks"; //
const String privacyTerms = "privacy-terms";
const String getShift = "delivery-man/shifts";
const String changeShift = "delivery-man/shifts-change";
const String helpSupport = "help-support";
const String assignOrderList = "delivery-man/delivassign"; //
const String orderDetails = "delivery-man/deliverydetails";
const String deliveryRespond = "delivery-man/deliveryrespond";
const String delivePickedupapi = "delivery-man/delive-pickedup";
const String deliveProof = "delivery-man/delive-proof";
const String announcements = "delivery-announcements";
const String notification = "delivery-man/getnotification";
const String feedback = "feedback-deliveries";
const String dispute = "dispute";
const String sos = "sos";
const String deliveryManWallet = "deliveryManWallet";
const String earningSummary = "deliveryManweeklySummary";
const String forgotPassword = "forgot-password";
const String reviewAvg = "review-ava";
const String proof = "  delivery-man/delive-proof";
const String license = "license";
const String licenseauth = "licenseauth";
const String dailySummary = "dailySummary";
const String sendotp = "auth/delivery-men/send-otp";
const String verifyotp = "auth/delivery-men/verify-otp";
const String walletSummary = "${baseUrl}summary";
const String sendWithdraw = "${baseUrl}withdraw";
const String pendingWid = "${baseUrl}my-withdrawals";